#!/usr/bin/env python3
"""Check structured cubic graph families (up to 62 vertices) against the
Erdős–Gyárfás conjecture using src/checker.

Families: generalized Petersen GP(m,k), prisms/Möbius ladders, and all
cubic Cayley graphs of groups of order <= 30 (via 3 involutions or an
involution plus a generator pair) — a cheap way to probe highly symmetric
graphs that exhaustive search cannot reach.
"""
import itertools
import subprocess
import networkx as nx
from networkx.readwrite.graph6 import to_graph6_bytes

graphs = []  # (name, g6)

def add(name, G):
    if G.number_of_nodes() > 62 or G.number_of_nodes() < 4:
        return
    if not all(d == 3 for _, d in G.degree()):
        return
    if not nx.is_connected(G):
        return
    g6 = to_graph6_bytes(G, header=False).decode().strip()
    graphs.append((name, g6))

# Generalized Petersen graphs GP(m,k), 3 <= m, 1 <= k < m/2
for m in range(3, 32):
    for k in range(1, (m - 1) // 2 + 1):
        G = nx.Graph()
        for i in range(m):
            G.add_edge(('o', i), ('o', (i + 1) % m))   # outer cycle
            G.add_edge(('i', i), ('i', (i + k) % m))   # inner star polygon
            G.add_edge(('o', i), ('i', i))             # spokes
        G = nx.convert_node_labels_to_integers(G)
        add(f"GP({m},{k})", G)

# Möbius ladders
for m in range(3, 32):
    add(f"Mobius({m})", nx.circulant_graph(2 * m, [1, m]))

# Cubic Cayley graphs of cyclic and dihedral groups of order <= 30,
# generated by connection sets closed under inverse with degree 3.
def cyclic_cayley(n):
    # connection set {a, -a, n/2} for even n
    if n % 2 == 0:
        for a in range(1, n // 2):
            yield f"Cay(Z{n},{{{a},{n//2}}})", nx.circulant_graph(n, [a, n // 2])

for n in range(4, 64, 2):
    for name, G in cyclic_cayley(n):
        add(name, G)

# run the checker
inp = "\n".join(g6 for _, g6 in graphs) + "\n"
res = subprocess.run(["./src/checker", "-a"], input=inp,
                     capture_output=True, text=True)
out = [l for l in res.stdout.splitlines() if l.startswith("G ")]
assert len(out) == len(graphs)
worst = []
for (name, g6), line in zip(graphs, out):
    val = int(line.split()[1])
    if val == 0:
        print(f"COUNTEREXAMPLE {name} {g6}")
        worst.append(name)
    elif val >= 16:
        print(f"  (first power {val}): {name}")
print(f"checked {len(graphs)} graphs from structured families; "
      f"counterexamples: {len(worst)}")
